const LOGIN = {
    INIT_AUTH: 'AUTH-INIT',
    AUTH_SUCCESS: 'AUTH-SUCCESS',
    AUTH_ERROR: 'AUTH-ERROR',
    LOGOUT: 'AUTH-LOGOUT'
}

const COORDS = {
    COORDS_SUCCESS: 'COORDS-SUCCESS',
    COORDS_ERROR: 'COORDS-ERROR',
}


export { LOGIN, COORDS }

